import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from 'react';
import { Link } from "react-router-dom";
import { RiUserShared2Line } from "react-icons/ri";
function Navbar() {
    const [menuOpen, setMenuOpen] = useState(false);
    const toggleMenu = () => setMenuOpen(!menuOpen);
    return (_jsxs("nav", { className: "relative", children: [_jsxs("ul", { className: "hidden md:flex gap-6 text-white text-lg font-semibold", children: [_jsx("li", { children: _jsx("a", { target: "_blank", rel: "noopener noreferrer", href: "https://jikan.moe/", children: "Jikan.API" }) }), _jsx("li", { children: _jsx("a", { target: "_blank", rel: "noopener noreferrer", href: "https://github.com/jhajathanawit/MissAnime", children: "GitHub" }) }), _jsx("li", { children: _jsx(Link, { to: "/MissAnime/contact", children: "Contact" }) }), _jsx("li", { children: _jsx(Link, { to: "/MissAnime/user/:id", children: _jsx(RiUserShared2Line, { className: "inline-block mr-1" }) }) })] }), _jsx("div", { className: "md:hidden flex items-center", children: _jsx("button", { id: "menu-toggle", className: "text-white focus:outline-none", onClick: toggleMenu, "aria-label": "Toggle menu", children: _jsx("svg", { className: "w-8 h-8", fill: "none", stroke: "currentColor", viewBox: "0 0 24 24", children: _jsx("path", { strokeLinecap: "round", strokeLinejoin: "round", strokeWidth: "2", d: "M4 6h16M4 12h16m-7 6h7" }) }) }) }), menuOpen && (_jsxs("ul", { className: "absolute right-0 mt-2 w-48 bg-[#1f2937] rounded-lg shadow-lg flex flex-col gap-4 p-4 z-50 md:hidden text-white text-lg font-semibold", children: [_jsx("li", { children: _jsx("a", { target: "_blank", rel: "noopener noreferrer", href: "https://jikan.moe/", children: "Jikan.API" }) }), _jsx("li", { children: _jsx("a", { target: "_blank", rel: "noopener noreferrer", href: "https://github.com/jhajathanawit/MissAnime", children: "GitHub" }) }), _jsx("li", { children: _jsx(Link, { to: "/MissAnime/contact", onClick: () => setMenuOpen(false), children: "Contact" }) }), _jsx("li", { children: _jsx(Link, { to: "/MissAnime/user/:id", onClick: () => setMenuOpen(false), children: _jsx(RiUserShared2Line, { className: "inline-block mr-1" }) }) })] }))] }));
}
export default Navbar;
